apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:io1Egkdxlq2YVzi+bTCw/H/vkhYqddbxUzeBYB4DTH1moGYmkw==,iv:UYwCC2gUo2bs1O6/AzTsuwJZpXtPxu4eulqwwgTPdLU=,tag:kegMBMLRxLq2u/Cr/V4tvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tefltm2x3t2pjsvdgys4400nlyysmdz9eew7fldre70ql0qukftqp4qja0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ajdpY3UwUzhuNklGcXpO
            UDJRWUJobVZRdjArRkw4THVzaHNXVFRXSndjCmtPNkR4Ym1vWm13aXQ3WXc5TThI
            akFQQ25WdUR2R0J3UXV0NTNYb2xYcHcKLS0tIERNeXRSUCtSbk9nakFtbFltdi9z
            MWMxbC84ZmlQbmVWVU9EV3JBNzJSMk0KAwbAFdzNlCPTWjoty9eilu+cqbPRBUY2
            HAVtblQdB/y5g8ElfpoNCoxIG3QnXh7z8r9FEd9nnlZoXhoSE9RV8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-13T17:27:56Z"
    mac: ENC[AES256_GCM,data:Itta3ii/r/Q+5HN2nqeLHfL0oEOI6e4WPHf+oJgF41Xsz/zJdJKiNuNBfytB0qDb8mIEaGejKPhgQeJATjjHMiWxieHMn2HH1TUCG8KXDmZ9kr6Z7QiOzi+SmgHUAaF04GURl8TGpcY/Vh/vPxYQpvG1AZY/v9CkaA+/Vg/XAt8=,iv:T/xeNqBRpG1uqSH/LSSHpNQPQxDP8/XU6b2F8qVb+ok=,tag:7PNIGSWTSfShn5bPmaOq+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
