apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:z5JxRzNA+JSmI3aNwbp/DXiuFHRIUJA=,iv:q9/AdrleFPU1O2Sc4d22do4czpJ25B4/D+cU6d8NRIU=,tag:wQuV8U5AZOQONi2c5hOTpA==,type:str]
    api-key: ENC[AES256_GCM,data:jVMnBlYFvZaEvVbn8jEW7qrU2bTwtlwC2oMvdv09pKWlk+h+Og==,iv:Ybq3jgOsMIH8A1xs6YXbQnTKMdVQBANeWr4EZfTOpFM=,tag:uSR76cq0gYMVRJSwNSESvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tefltm2x3t2pjsvdgys4400nlyysmdz9eew7fldre70ql0qukftqp4qja0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoU1dOUXlVUC9JTDA4SFBi
            Z2E0cVF0cnpBTkwxQnNONDVOUVcrSWFESVZvCmRTUkNONm9BYjZtMHc5WDNTeTV2
            VGNqdFdBdUtiajVLNkZING5aZkh6Zk0KLS0tIE1hOXlqblk4dEREaDE2N2t5VkZO
            S3l5R2MrM3JvU1hLb2VlN0FZTVB6b1EKuF7FzhIctmX4p4HLqOQO5Cvqe9V89pCB
            wEozLV/BePb8Y/bnckp+fo/lhYJY8VhPS8ln+FUYmP6elSMqDyEqNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-13T17:27:56Z"
    mac: ENC[AES256_GCM,data:rKK9xU0Tq21SIZr6xtSJY4PBVc8mbTrlVX84Mu/xavgC22pyYQZkv+nM/uNkcpGAMfmuXVQ4sWY9ZvL+2vXcYfUYM5ENaKd//+25fH0bobTlig+G/OC7GgqWS0EF35ElMokfQLmfFtyciugDGnE1W/XJnR3fjD0NcGW6Dq7DUPQ=,iv:rpmUYJQTzma4Cd2i49BW6+WRp198Kkn28CrKjNNDiqI=,tag:iwPrH7AYV9yhv2pfOds/Zw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
