---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Denver"
  KUBE_VIP_ADDR: "192.168.30.105"
  METALLB_LB_RANGE: "192.168.30.150-192.168.30.160"
  METALLB_K8S_GATEWAY_ADDR: "192.168.30.150"
  METALLB_INGRESS_ADDR: "192.168.30.151"
